### ISSUE TITLE
Les nouvelles icônes de stations rendent l'utilisation des entités dans une carte "map" inutile

### ISSUE THREAD

**Issue by KodWhat** [Aohzan/hass-prixcarburant#19]
**Describe the bug**
Suite à l'ajout des icônes de stations, le composants HA "map" affiche l'icône de la station au lieu d'utiliser la valeur de "label_mode" dans la configuration, cassant ainsi le moyen de visualiser rapidement le prix du carburant sur une carte.

Si le bug d'affichage provient de HA, il faudrait a minima une configuration permettant de désactiver les icônes des stations afin de retrouver un comportement rendant les entités utilisables sur une carte

**Configuration**
Configuration d'exemple :
```yaml
type: map
entities:
  - entity: sensor.station_xyz
    label_mode: state
    focus: false
default_zoom: 11
auto_fit: false
dark_mode: false
```

**Expected behavior**
Le composant "map" devrait afficher le prix au lieu de l'icône.

**Screenshots**
![image](https://github.com/Aohzan/hass-prixcarburant/assets/1282471/bed75b51-25ee-4439-adfb-8be38da6ae67)
Avant MaJ 3.0.0, le prix était indiqué en utilisant label_mode: state. Après MaJ, seul l'icône apparait, le prix n'apparait plus.

**Debug logs**
_Aucun, problème dans la visualisation des données de l'entité_
