### ISSUE TITLE
Some station name contain address

### ISSUE THREAD

**Issue by Desaydrone** [Aohzan/hass-prixcarburant#3]
Hello,

With some gaz station in flex-table-card i got some address

```yaml
type: custom:flex-table-card
clickable: true
sort_by: state
max_rows: 2
title: Carburant
entities:
  include: sensor.station*sp95
columns:
  - name: Station
    data: name
    icon: mdi:gas-station
  - name: SP95 €/L
    data: state
  - name: ' '
    data: updated_date
    align: right
css:
  tbody tr:nth-child(odd): 'background-color: rgba(255, 255, 255, 0.2)'
  tbody tr:nth-child(even): 'background-color: rgba(255, 255, 255, 0.1)'
  tbody tr:nth-child(1): 'color: #00ff00'
  tbody tr:nth-child(2): 'color: #FF0000'
card_mod: null
style: |
  :host {
    font-size: 13px;
    /*border-radius: 10px;
    border-style: solid;
    border-width: 2px 2px 0px 2px;
    border-color: #ffffff;*/
  }

```

And the result look like this : 

![image](https://user-images.githubusercontent.com/15471688/180593778-9d7a4d06-e279-42b0-9cbd-6974ed3be2e1.png)

I the dev panel the name and address are ine the field name, if you want to test here the id of the station : 29196001
