### ISSUE TITLE
entities not updating

### ISSUE THREAD

**Issue by cxFreeze** [Aohzan/hass-prixcarburant#4]
hi, my entities are not updating (unless i reboot ha)

![screenshot295](https://user-images.githubusercontent.com/19434393/180617263-7dc55e7c-cf47-42ac-b38f-771a0c0563d5.png)

`  - platform: prix_carburant
    stations:
      - xxxxxxxxx
      - xxxxxxxxx`

do you know what can i do ?

thanks

**Comment by ManTreff** [comment]
Salut, j'ai le mm problème. En rechargeant l'intégration ca se met a jours...

**Comment by tikismoke** [comment]
Pareil obligé de recharger l'intégration.

**Comment by Quentame** [comment]
Hi !

That's actually a big issue indeed.

I personally update all entities at once by reloading the config entry with an automation, at specific times.


Here is how to do this:
```yaml
alias: UPDATE - Prix carburant
trigger:
  - platform: time
    at: "08:00:00"
  - platform: time
    at: "18:00:00"
action:
  - service: homeassistant.reload_config_entry
    target:
      entity_id: sensor.station_XXX
mode: single
```
Update the automation as you wish.
`homeassistant.reload_config_entry` requires only one entity to update all the config, adding more is useless.

De rien 😉
