### ISSUE TITLE
Créer une carte et indiquer les stations autour d'un device movible

### ISSUE THREAD

**Issue by Master13011** [Aohzan/hass-prixcarburant#84]
**Describe the bug**
Aucune donnée ne s'affiche dans le sensor gps_stations, pourtant il y a bien des données dans la variable stations_feed

**Configuration**
```- platform: template
  sensors:
    gps_stations:
        friendly_name: "Stations Proches"
        unique_id: gps_stations
        value_template: "{{ now().isoformat() }}"
        attribute_templates:
          stations: "{{ stations_feed.stations }}"```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
![{89BFF411-35CC-4B4E-84A2-B44668309D23}](https://github.com/user-attachments/assets/6ea5c296-c4fb-4226-b59f-e6f24510d847)
![{0FCCF37B-5B98-4E1E-A8BC-8A23C05010C7}](https://github.com/user-attachments/assets/9f5fc986-83d9-405e-9f6e-4357efd82b24)
![{D653FACE-43C0-4729-B0CD-E1D7F98700C1}](https://github.com/user-attachments/assets/e91f713f-d9cf-4a7a-b7ab-98b66fb4566f)

**Debug logs**
![image](https://github.com/Aohzan/ipx800v5/assets/2736322/4e2a69a3-db12-4c6d-9aa5-a96aa2e4a2e1)
```
![{F87C8195-4D15-47DC-BB7D-59C0A140FB67}](https://github.com/user-attachments/assets/6209cd05-d622-4f96-b089-76be25bb8104)
```

**Comment by Aohzan** [comment]
La variable `stations_feed` n'est pas transmise entre ton automation et ton sensor template, il faut que le trigger et l'appel de l'action soit fait dans le sensor, je n'ai pas d'exemple par contre

**Comment by Master13011** [comment]
Yes en effet, ca fonctionne ! 

J'ai ajouter la config ci-dessous dans le fichier : /homeassistant/template.yaml

```
  - trigger:
      - platform: time_pattern
        minutes: /1
    action:
      - action: prix_carburant.find_nearest_stations
        data:
          distance: 10
          entity_id: device_tracker.XX
          fuel: SP95
        response_variable: stations_feed
    sensor:
      - name: gps_stations
        unique_id: gps_stations
        state: "{{ now().isoformat() }}"
        attributes:        
            stations: "{{ stations_feed.stations }}"
```

![{0DCBE642-25BF-4B79-9537-11AC705238C5}](https://github.com/user-attachments/assets/f1f6fc05-ed9d-46bc-b815-d5d63ab361d7)


Merci !
